In [2]:
# Dependencies
import pandas as pd

In [3]:
file = "team/total_team_stats.csv"

df = pd.read_csv(file)
df.head()

,variable,1st Downs,1st downs by penalty,3rd down %,3rd down efficiency,4th down %,4th down efficiency,Average Interception Yards,Average Kickoff Return Yards,Average Punt Return Yards,...,Total Points,Total Points Per Game,Total Touchdowns,Total Yards,Total-Yards,Touchback Percentage,Turnover Ratio,Yards Per Game,Yards Per Pass Attempt,Yards Per Rush Attempt
0,Cincinnati,290,21,42.99,92-214,64.71,11-17,18.8,21.9,8.3,...,413,31.8,52,5464,123-977,0,17-9,390.3,6.8,4.7
1,East Carolina,288,37,39.33,70-178,42.86,3-7,9.8,16.3,5.3,...,321,26.8,36,5162,71-615,0,0,430.2,7.7,3.8
2,Houston,232,23,34.84,54-155,70.59,12-17,10.4,21.7,11.4,...,368,30.7,44,4698,58-579,0,0,391.5,7.8,4.8
3,Memphis,327,31,45.88,89-194,58.33,14-24,4.8,26.2,8.1,...,566,40.4,71,6791,103-839,0,21-9,485.1,9.5,4.7
4,Navy,282,12,46.20,79-171,76.47,26-34,4.8,16.9,6.2,...,483,37.2,64,5925,54-459,0,20-12,455.8,11.9,6.1

In [4]:
#replace spaces with underscores
df.columns = df.columns.str.replace(' ', '_')
df.head()

,variable,1st_Downs,1st_downs_by_penalty,3rd_down_%,3rd_down_efficiency,4th_down_%,4th_down_efficiency,Average_Interception_Yards,Average_Kickoff_Return_Yards,Average_Punt_Return_Yards,...,Total_Points,Total_Points_Per_Game,Total_Touchdowns,Total_Yards,Total-Yards,Touchback_Percentage,Turnover_Ratio,Yards_Per_Game,Yards_Per_Pass_Attempt,Yards_Per_Rush_Attempt
0,Cincinnati,290,21,42.99,92-214,64.71,11-17,18.8,21.9,8.3,...,413,31.8,52,5464,123-977,0,17-9,390.3,6.8,4.7
1,East Carolina,288,37,39.33,70-178,42.86,3-7,9.8,16.3,5.3,...,321,26.8,36,5162,71-615,0,0,430.2,7.7,3.8
2,Houston,232,23,34.84,54-155,70.59,12-17,10.4,21.7,11.4,...,368,30.7,44,4698,58-579,0,0,391.5,7.8,4.8
3,Memphis,327,31,45.88,89-194,58.33,14-24,4.8,26.2,8.1,...,566,40.4,71,6791,103-839,0,21-9,485.1,9.5,4.7
4,Navy,282,12,46.20,79-171,76.47,26-34,4.8,16.9,6.2,...,483,37.2,64,5925,54-459,0,20-12,455.8,11.9,6.1

In [5]:
#lowercase all column headers
df.columns = map(str.lower, df.columns)
df.head()

,variable,1st_downs,1st_downs_by_penalty,3rd_down_%,3rd_down_efficiency,4th_down_%,4th_down_efficiency,average_interception_yards,average_kickoff_return_yards,average_punt_return_yards,...,total_points,total_points_per_game,total_touchdowns,total_yards,total-yards,touchback_percentage,turnover_ratio,yards_per_game,yards_per_pass_attempt,yards_per_rush_attempt
0,Cincinnati,290,21,42.99,92-214,64.71,11-17,18.8,21.9,8.3,...,413,31.8,52,5464,123-977,0,17-9,390.3,6.8,4.7
1,East Carolina,288,37,39.33,70-178,42.86,3-7,9.8,16.3,5.3,...,321,26.8,36,5162,71-615,0,0,430.2,7.7,3.8
2,Houston,232,23,34.84,54-155,70.59,12-17,10.4,21.7,11.4,...,368,30.7,44,4698,58-579,0,0,391.5,7.8,4.8
3,Memphis,327,31,45.88,89-194,58.33,14-24,4.8,26.2,8.1,...,566,40.4,71,6791,103-839,0,21-9,485.1,9.5,4.7
4,Navy,282,12,46.20,79-171,76.47,26-34,4.8,16.9,6.2,...,483,37.2,64,5925,54-459,0,20-12,455.8,11.9,6.1

In [6]:
#drop some bad data columns
drop = df.drop(columns=['3rd_down_efficiency', '4th_down_efficiency', 'touchback_percentage', 'possession_time_seconds', 'turnover_ratio'])
drop.head()

,variable,1st_downs,1st_downs_by_penalty,3rd_down_%,4th_down_%,average_interception_yards,average_kickoff_return_yards,average_punt_return_yards,comp-att,fg:_good-attempts,...,sacks-yards_lost,total_offensive_plays,total_points,total_points_per_game,total_touchdowns,total_yards,total-yards,yards_per_game,yards_per_pass_attempt,yards_per_rush_attempt
0,Cincinnati,290,21,42.99,64.71,18.8,21.9,8.3,208-377,16-22,...,35--234,1028,413,31.8,52,5464,123-977,390.3,6.8,4.7
1,East Carolina,288,37,39.33,42.86,9.8,16.3,5.3,270-451,24-29,...,17--150,917,321,26.8,36,5162,71-615,430.2,7.7,3.8
2,Houston,232,23,34.84,70.59,10.4,21.7,11.4,176-314,20-24,...,35--199,815,368,30.7,44,4698,58-579,391.5,7.8,4.8
3,Memphis,327,31,45.88,58.33,4.8,26.2,8.1,281-441,23-25,...,27--170,1019,566,40.4,71,6791,103-839,485.1,9.5,4.7
4,Navy,282,12,46.20,76.47,4.8,16.9,6.2,55-104,12-17,...,17--95,894,483,37.2,64,5925,54-459,455.8,11.9,6.1

In [7]:
#rename some columns
renamed = drop.rename(columns={"1st_downs":"first_downs", 
                               "1st_downs_by_penalty":"first_downs_by_penalty", 
                               "3rd_down_%":"third_down_percentage", 
                               "4th_down_%":"fourth_down_percentage", 
                               "comp-att":"comp_att", 
                               "fg:_good-attempts":"fg_good_attempt", 
                               "fumbles-lost":"fumbles_lost", 
                               "int:_total":"int_total", 
                               "kickoffs:_total":"kickoffs_total", 
                               "passing_1st_downs":"passing_first_downs",
                               "punt:_total":"punt_total",
                               "punt:_total_yards":"punt_total_yards",
                               "rushing_1st_downs":"rushing_first_downs",
                               "sacks-yards_lost":"sacks_yards_lost",
                               "total-yards":"total_penalties_yards",
                               "total_yards":"total_offensive_yards"
                              })
renamed.head()

,variable,first_downs,first_downs_by_penalty,third_down_percentage,fourth_down_percentage,average_interception_yards,average_kickoff_return_yards,average_punt_return_yards,comp_att,fg_good_attempt,...,sacks_yards_lost,total_offensive_plays,total_points,total_points_per_game,total_touchdowns,total_offensive_yards,total_penalties_yards,yards_per_game,yards_per_pass_attempt,yards_per_rush_attempt
0,Cincinnati,290,21,42.99,64.71,18.8,21.9,8.3,208-377,16-22,...,35--234,1028,413,31.8,52,5464,123-977,390.3,6.8,4.7
1,East Carolina,288,37,39.33,42.86,9.8,16.3,5.3,270-451,24-29,...,17--150,917,321,26.8,36,5162,71-615,430.2,7.7,3.8
2,Houston,232,23,34.84,70.59,10.4,21.7,11.4,176-314,20-24,...,35--199,815,368,30.7,44,4698,58-579,391.5,7.8,4.8
3,Memphis,327,31,45.88,58.33,4.8,26.2,8.1,281-441,23-25,...,27--170,1019,566,40.4,71,6791,103-839,485.1,9.5,4.7
4,Navy,282,12,46.20,76.47,4.8,16.9,6.2,55-104,12-17,...,17--95,894,483,37.2,64,5925,54-459,455.8,11.9,6.1

In [8]:
#list all renamed columns before splitting up data in certain columns
renamed.columns.tolist()

['variable',
 'first_downs',
 'first_downs_by_penalty',
 'third_down_percentage',
 'fourth_down_percentage',
 'average_interception_yards',
 'average_kickoff_return_yards',
 'average_punt_return_yards',
 'comp_att',
 'fg_good_attempt',
 'fumbles_lost',
 'int_total',
 'interceptions',
 'kickoffs_total',
 'net_average_punt_yards',
 'net_passing_yards',
 'net_passing_yards_per_game',
 'passing_first_downs',
 'passing_touchdowns',
 'punt_total',
 'punt_total_yards',
 'rushing_first_downs',
 'rushing_attempts',
 'rushing_touchdowns',
 'rushing_yards',
 'rushing_yards_per_game',
 'sacks_yards_lost',
 'total_offensive_plays',
 'total_points',
 'total_points_per_game',
 'total_touchdowns',
 'total_offensive_yards',
 'total_penalties_yards',
 'yards_per_game',
 'yards_per_pass_attempt',
 'yards_per_rush_attempt']

In [9]:
#start splitting some data into two columns
renamed[['completed_passes','attempted_passes']] = renamed.comp_att.str.split("-",expand=True)
renamed.head()

,variable,first_downs,first_downs_by_penalty,third_down_percentage,fourth_down_percentage,average_interception_yards,average_kickoff_return_yards,average_punt_return_yards,comp_att,fg_good_attempt,...,total_points,total_points_per_game,total_touchdowns,total_offensive_yards,total_penalties_yards,yards_per_game,yards_per_pass_attempt,yards_per_rush_attempt,completed_passes,attempted_passes
0,Cincinnati,290,21,42.99,64.71,18.8,21.9,8.3,208-377,16-22,...,413,31.8,52,5464,123-977,390.3,6.8,4.7,208,377
1,East Carolina,288,37,39.33,42.86,9.8,16.3,5.3,270-451,24-29,...,321,26.8,36,5162,71-615,430.2,7.7,3.8,270,451
2,Houston,232,23,34.84,70.59,10.4,21.7,11.4,176-314,20-24,...,368,30.7,44,4698,58-579,391.5,7.8,4.8,176,314
3,Memphis,327,31,45.88,58.33,4.8,26.2,8.1,281-441,23-25,...,566,40.4,71,6791,103-839,485.1,9.5,4.7,281,441
4,Navy,282,12,46.20,76.47,4.8,16.9,6.2,55-104,12-17,...,483,37.2,64,5925,54-459,455.8,11.9,6.1,55,104

In [10]:
renamed[['field_goals_completed','field_goals_attempted']] = renamed.fg_good_attempt.str.split("-",expand=True)
renamed.head()

,variable,first_downs,first_downs_by_penalty,third_down_percentage,fourth_down_percentage,average_interception_yards,average_kickoff_return_yards,average_punt_return_yards,comp_att,fg_good_attempt,...,total_touchdowns,total_offensive_yards,total_penalties_yards,yards_per_game,yards_per_pass_attempt,yards_per_rush_attempt,completed_passes,attempted_passes,field_goals_completed,field_goals_attempted
0,Cincinnati,290,21,42.99,64.71,18.8,21.9,8.3,208-377,16-22,...,52,5464,123-977,390.3,6.8,4.7,208,377,16,22
1,East Carolina,288,37,39.33,42.86,9.8,16.3,5.3,270-451,24-29,...,36,5162,71-615,430.2,7.7,3.8,270,451,24,29
2,Houston,232,23,34.84,70.59,10.4,21.7,11.4,176-314,20-24,...,44,4698,58-579,391.5,7.8,4.8,176,314,20,24
3,Memphis,327,31,45.88,58.33,4.8,26.2,8.1,281-441,23-25,...,71,6791,103-839,485.1,9.5,4.7,281,441,23,25
4,Navy,282,12,46.20,76.47,4.8,16.9,6.2,55-104,12-17,...,64,5925,54-459,455.8,11.9,6.1,55,104,12,17

In [11]:
renamed[['total_fumbles','fumbles_lost']] = renamed["fumbles_lost"].str.replace(':', '-').str.split("-", expand=True)
renamed.head()

,variable,first_downs,first_downs_by_penalty,third_down_percentage,fourth_down_percentage,average_interception_yards,average_kickoff_return_yards,average_punt_return_yards,comp_att,fg_good_attempt,...,total_offensive_yards,total_penalties_yards,yards_per_game,yards_per_pass_attempt,yards_per_rush_attempt,completed_passes,attempted_passes,field_goals_completed,field_goals_attempted,total_fumbles
0,Cincinnati,290,21,42.99,64.71,18.8,21.9,8.3,208-377,16-22,...,5464,123-977,390.3,6.8,4.7,208,377,16,22,41
1,East Carolina,288,37,39.33,42.86,9.8,16.3,5.3,270-451,24-29,...,5162,71-615,430.2,7.7,3.8,270,451,24,29,15
2,Houston,232,23,34.84,70.59,10.4,21.7,11.4,176-314,20-24,...,4698,58-579,391.5,7.8,4.8,176,314,20,24,17
3,Memphis,327,31,45.88,58.33,4.8,26.2,8.1,281-441,23-25,...,6791,103-839,485.1,9.5,4.7,281,441,23,25,32
4,Navy,282,12,46.20,76.47,4.8,16.9,6.2,55-104,12-17,...,5925,54-459,455.8,11.9,6.1,55,104,12,17,36

In [12]:
renamed[['defensive_interception','yards_after_interception']] = renamed["int_total"].str.split("-", expand=True)
renamed.head()

,variable,first_downs,first_downs_by_penalty,third_down_percentage,fourth_down_percentage,average_interception_yards,average_kickoff_return_yards,average_punt_return_yards,comp_att,fg_good_attempt,...,yards_per_game,yards_per_pass_attempt,yards_per_rush_attempt,completed_passes,attempted_passes,field_goals_completed,field_goals_attempted,total_fumbles,defensive_interception,yards_after_interception
0,Cincinnati,290,21,42.99,64.71,18.8,21.9,8.3,208-377,16-22,...,390.3,6.8,4.7,208,377,16,22,41,16,300
1,East Carolina,288,37,39.33,42.86,9.8,16.3,5.3,270-451,24-29,...,430.2,7.7,3.8,270,451,24,29,15,11,108
2,Houston,232,23,34.84,70.59,10.4,21.7,11.4,176-314,20-24,...,391.5,7.8,4.8,176,314,20,24,17,8,83
3,Memphis,327,31,45.88,58.33,4.8,26.2,8.1,281-441,23-25,...,485.1,9.5,4.7,281,441,23,25,32,11,53
4,Navy,282,12,46.20,76.47,4.8,16.9,6.2,55-104,12-17,...,455.8,11.9,6.1,55,104,12,17,36,12,57

In [13]:
renamed[['total_kickoffs_received','yards_off_kickoff_received']] = renamed["kickoffs_total"].str.split("-", expand=True)
renamed.head()

,variable,first_downs,first_downs_by_penalty,third_down_percentage,fourth_down_percentage,average_interception_yards,average_kickoff_return_yards,average_punt_return_yards,comp_att,fg_good_attempt,...,yards_per_rush_attempt,completed_passes,attempted_passes,field_goals_completed,field_goals_attempted,total_fumbles,defensive_interception,yards_after_interception,total_kickoffs_received,yards_off_kickoff_received
0,Cincinnati,290,21,42.99,64.71,18.8,21.9,8.3,208-377,16-22,...,4.7,208,377,16,22,41,16,300,27,590
1,East Carolina,288,37,39.33,42.86,9.8,16.3,5.3,270-451,24-29,...,3.8,270,451,24,29,15,11,108,40,653
2,Houston,232,23,34.84,70.59,10.4,21.7,11.4,176-314,20-24,...,4.8,176,314,20,24,17,8,83,26,564
3,Memphis,327,31,45.88,58.33,4.8,26.2,8.1,281-441,23-25,...,4.7,281,441,23,25,32,11,53,46,1206
4,Navy,282,12,46.20,76.47,4.8,16.9,6.2,55-104,12-17,...,6.1,55,104,12,17,36,12,57,13,220

In [14]:
renamed[['total_punts_received','yards_off_punts_received']] = renamed["punt_total"].str.split("-", expand=True)
renamed.head()

,variable,first_downs,first_downs_by_penalty,third_down_percentage,fourth_down_percentage,average_interception_yards,average_kickoff_return_yards,average_punt_return_yards,comp_att,fg_good_attempt,...,attempted_passes,field_goals_completed,field_goals_attempted,total_fumbles,defensive_interception,yards_after_interception,total_kickoffs_received,yards_off_kickoff_received,total_punts_received,yards_off_punts_received
0,Cincinnati,290,21,42.99,64.71,18.8,21.9,8.3,208-377,16-22,...,377,16,22,41,16,300,27,590,30,250
1,East Carolina,288,37,39.33,42.86,9.8,16.3,5.3,270-451,24-29,...,451,24,29,15,11,108,40,653,15,79
2,Houston,232,23,34.84,70.59,10.4,21.7,11.4,176-314,20-24,...,314,20,24,17,8,83,26,564,16,182
3,Memphis,327,31,45.88,58.33,4.8,26.2,8.1,281-441,23-25,...,441,23,25,32,11,53,46,1206,25,187
4,Navy,282,12,46.20,76.47,4.8,16.9,6.2,55-104,12-17,...,104,12,17,36,12,57,13,220,18,112

In [15]:
renamed[['total_punts_kicked','total_punt_yards']] = renamed["punt_total_yards"].str.split("-", expand=True)
renamed.head()

,variable,first_downs,first_downs_by_penalty,third_down_percentage,fourth_down_percentage,average_interception_yards,average_kickoff_return_yards,average_punt_return_yards,comp_att,fg_good_attempt,...,field_goals_attempted,total_fumbles,defensive_interception,yards_after_interception,total_kickoffs_received,yards_off_kickoff_received,total_punts_received,yards_off_punts_received,total_punts_kicked,total_punt_yards
0,Cincinnati,290,21,42.99,64.71,18.8,21.9,8.3,208-377,16-22,...,22,41,16,300,27,590,30,250,72,3053
1,East Carolina,288,37,39.33,42.86,9.8,16.3,5.3,270-451,24-29,...,29,15,11,108,40,653,15,79,65,2653
2,Houston,232,23,34.84,70.59,10.4,21.7,11.4,176-314,20-24,...,24,17,8,83,26,564,16,182,54,2531
3,Memphis,327,31,45.88,58.33,4.8,26.2,8.1,281-441,23-25,...,25,32,11,53,46,1206,25,187,44,1957
4,Navy,282,12,46.20,76.47,4.8,16.9,6.2,55-104,12-17,...,17,36,12,57,13,220,18,112,39,1668

In [16]:
renamed[['total_defensive_sacks','yards_lost_from_sacks']] = renamed["sacks_yards_lost"].str.split("--", expand=True)
renamed.head()

,variable,first_downs,first_downs_by_penalty,third_down_percentage,fourth_down_percentage,average_interception_yards,average_kickoff_return_yards,average_punt_return_yards,comp_att,fg_good_attempt,...,defensive_interception,yards_after_interception,total_kickoffs_received,yards_off_kickoff_received,total_punts_received,yards_off_punts_received,total_punts_kicked,total_punt_yards,total_defensive_sacks,yards_lost_from_sacks
0,Cincinnati,290,21,42.99,64.71,18.8,21.9,8.3,208-377,16-22,...,16,300,27,590,30,250,72,3053,35,234
1,East Carolina,288,37,39.33,42.86,9.8,16.3,5.3,270-451,24-29,...,11,108,40,653,15,79,65,2653,17,150
2,Houston,232,23,34.84,70.59,10.4,21.7,11.4,176-314,20-24,...,8,83,26,564,16,182,54,2531,35,199
3,Memphis,327,31,45.88,58.33,4.8,26.2,8.1,281-441,23-25,...,11,53,46,1206,25,187,44,1957,27,170
4,Navy,282,12,46.20,76.47,4.8,16.9,6.2,55-104,12-17,...,12,57,13,220,18,112,39,1668,17,95

In [32]:
renamed[['total_penalties','total_yards_penalized']] = renamed["total_penalties_yards"].str.split("-", expand=True)
renamed.head()

,variable,first_downs,first_downs_by_penalty,third_down_percentage,fourth_down_percentage,average_interception_yards,average_kickoff_return_yards,average_punt_return_yards,comp_att,fg_good_attempt,...,total_kickoffs_received,yards_off_kickoff_received,total_punts_received,yards_off_punts_received,total_punts_kicked,total_punt_yards,total_defensive_sacks,yards_lost_from_sacks,total_penalties,total_yards_penalized
0,Cincinnati,290,21,42.99,64.71,18.8,21.9,8.3,208-377,16-22,...,27,590,30,250,72,3053,35,234,123,977
1,East Carolina,288,37,39.33,42.86,9.8,16.3,5.3,270-451,24-29,...,40,653,15,79,65,2653,17,150,71,615
2,Houston,232,23,34.84,70.59,10.4,21.7,11.4,176-314,20-24,...,26,564,16,182,54,2531,35,199,58,579
3,Memphis,327,31,45.88,58.33,4.8,26.2,8.1,281-441,23-25,...,46,1206,25,187,44,1957,27,170,103,839
4,Navy,282,12,46.20,76.47,4.8,16.9,6.2,55-104,12-17,...,13,220,18,112,39,1668,17,95,54,459

In [33]:
#list all columns
renamed.columns.tolist()

['variable',
 'first_downs',
 'first_downs_by_penalty',
 'third_down_percentage',
 'fourth_down_percentage',
 'average_interception_yards',
 'average_kickoff_return_yards',
 'average_punt_return_yards',
 'comp_att',
 'fg_good_attempt',
 'fumbles_lost',
 'int_total',
 'interceptions',
 'kickoffs_total',
 'net_average_punt_yards',
 'net_passing_yards',
 'net_passing_yards_per_game',
 'passing_first_downs',
 'passing_touchdowns',
 'punt_total',
 'punt_total_yards',
 'rushing_first_downs',
 'rushing_attempts',
 'rushing_touchdowns',
 'rushing_yards',
 'rushing_yards_per_game',
 'sacks_yards_lost',
 'total_offensive_plays',
 'total_points',
 'total_points_per_game',
 'total_touchdowns',
 'total_offensive_yards',
 'total_penalties_yards',
 'yards_per_game',
 'yards_per_pass_attempt',
 'yards_per_rush_attempt',
 'completed_passes',
 'attempted_passes',
 'field_goals_completed',
 'field_goals_attempted',
 'total_fumbles',
 'defensive_interception',
 'yards_after_interception',
 'total_kickoffs_received',
 'yards_off_kickoff_received',
 'total_punts_received',
 'yards_off_punts_received',
 'total_punts_kicked',
 'total_punt_yards',
 'total_defensive_sacks',
 'yards_lost_from_sacks',
 'total_penalties',
 'total_yards_penalized']

In [34]:
#drop old columns
team_stats = renamed.drop(columns=['comp_att', 'fg_good_attempt', 'fumbles_lost', 'int_total', 'kickoffs_total', 'punt_total','punt_total_yards','sacks_yards_lost','total_penalties_yards'])

In [35]:
#confirm new columns
team_stats.columns.tolist()

['variable',
 'first_downs',
 'first_downs_by_penalty',
 'third_down_percentage',
 'fourth_down_percentage',
 'average_interception_yards',
 'average_kickoff_return_yards',
 'average_punt_return_yards',
 'interceptions',
 'net_average_punt_yards',
 'net_passing_yards',
 'net_passing_yards_per_game',
 'passing_first_downs',
 'passing_touchdowns',
 'rushing_first_downs',
 'rushing_attempts',
 'rushing_touchdowns',
 'rushing_yards',
 'rushing_yards_per_game',
 'total_offensive_plays',
 'total_points',
 'total_points_per_game',
 'total_touchdowns',
 'total_offensive_yards',
 'yards_per_game',
 'yards_per_pass_attempt',
 'yards_per_rush_attempt',
 'completed_passes',
 'attempted_passes',
 'field_goals_completed',
 'field_goals_attempted',
 'total_fumbles',
 'defensive_interception',
 'yards_after_interception',
 'total_kickoffs_received',
 'yards_off_kickoff_received',
 'total_punts_received',
 'yards_off_punts_received',
 'total_punts_kicked',
 'total_punt_yards',
 'total_defensive_sacks',
 'yards_lost_from_sacks',
 'total_penalties',
 'total_yards_penalized']

In [36]:
#new clean team_stats to csv
team_stats.to_csv("team/cleaned_team_stats.csv")