In [15]:
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

In [16]:
df = pd.read_csv("clean_team_stats.csv")
# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')
# Drop the null rows
#df = df.dropna()
df.head()

,team_no,variable,first_downs,first_downs_by_penalty,third_down_percentage,fourth_down_percentage,average_interception_yards,average_kickoff_return_yards,average_punt_return_yards,interceptions,...,yards_per_game,yards_per_pass_attempt,yards_per_rush_attempt,total_penalties,total_yards_penalized,total_defensive_sacks,yards_lost_from_sacks,total_punts_kicked,total_punt_yards,total_team_penalties
0,0,Cincinnati,290,21,42.99,64.71,18.8,21.9,8.3,11,...,390.3,6.8,4.7,123,977,35,234,72,3053,123
1,1,East Carolina,288,37,39.33,42.86,9.8,16.3,5.3,10,...,430.2,7.7,3.8,71,615,17,150,65,2653,71
2,2,Houston,232,23,34.84,70.59,10.4,21.7,11.4,12,...,391.5,7.8,4.8,58,579,35,199,54,2531,58
3,3,Memphis,327,31,45.88,58.33,4.8,26.2,8.1,11,...,485.1,9.5,4.7,103,839,27,170,44,1957,103
4,4,Navy,282,12,46.20,76.47,4.8,16.9,6.2,4,...,455.8,11.9,6.1,54,459,17,95,39,1668,54

In [17]:
df.dtypes

team_no                           int64
variable                         object
first_downs                       int64
first_downs_by_penalty            int64
third_down_percentage           float64
fourth_down_percentage          float64
average_interception_yards      float64
average_kickoff_return_yards    float64
average_punt_return_yards       float64
interceptions                     int64
net_average_punt_yards          float64
net_passing_yards                 int64
net_passing_yards_per_game      float64
passing_first_downs               int64
passing_touchdowns                int64
rushing_first_downs               int64
rushing_attempts                  int64
rushing_touchdowns                int64
rushing_yards                     int64
rushing_yards_per_game          float64
total_offensive_plays             int64
total_points                      int64
total_points_per_game           float64
total_touchdowns                  int64
total_offensive_yards             int64
total_penalties_yards            object
yards_per_game                  float64
yards_per_pass_attempt          float64
yards_per_rush_attempt          float64
total_penalties                   int64
total_yards_penalized             int64
total_defensive_sacks             int64
yards_lost_from_sacks             int64
total_punts_kicked                int64
total_punt_yards                  int64
total_team_penalties              int64
dtype: object

In [18]:
df=df.drop(['team_no','variable', 'total_penalties_yards'], axis=1)

In [19]:
df.dtypes

first_downs                       int64
first_downs_by_penalty            int64
third_down_percentage           float64
fourth_down_percentage          float64
average_interception_yards      float64
average_kickoff_return_yards    float64
average_punt_return_yards       float64
interceptions                     int64
net_average_punt_yards          float64
net_passing_yards                 int64
net_passing_yards_per_game      float64
passing_first_downs               int64
passing_touchdowns                int64
rushing_first_downs               int64
rushing_attempts                  int64
rushing_touchdowns                int64
rushing_yards                     int64
rushing_yards_per_game          float64
total_offensive_plays             int64
total_points                      int64
total_points_per_game           float64
total_touchdowns                  int64
total_offensive_yards             int64
yards_per_game                  float64
yards_per_pass_attempt          float64
yards_per_rush_attempt          float64
total_penalties                   int64
total_yards_penalized             int64
total_defensive_sacks             int64
yards_lost_from_sacks             int64
total_punts_kicked                int64
total_punt_yards                  int64
total_team_penalties              int64
dtype: object

In [20]:
FIELDS_TO_DROP = ['first_downs', 'third_down_percentage', 'yards_per_rush_attempt', 'rushing_touchdowns',
                 'passing_touchdowns']

In [21]:
X = df.drop(FIELDS_TO_DROP, 1).dropna().drop_duplicates()
y = df[["first_downs","third_down_percentage"]].values
print(X.shape, y.shape)

(130, 28) (130, 2)

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [23]:
parameters = {'bootstrap': False,
              'min_samples_leaf': 3,
              'n_estimators': 50,
              'min_samples_split': 10,
              'max_features': 'sqrt',
              'max_depth': 6}
model = RandomForestRegressor(**parameters)
model.fit(X_train, y_train)
print(model.predict(X_test).astype(int), y_test)

[[288  43]
 [241  35]
 [289  41]
 [283  43]
 [255  38]
 [220  34]
 [256  38]
 [269  40]
 [343  47]
 [280  41]
 [258  38]
 [318  44]
 [295  41]
 [254  38]
 [196  32]
 [255  38]
 [314  44]
 [303  43]
 [238  36]
 [241  36]
 [278  41]
 [268  41]
 [249  36]
 [232  35]
 [293  41]
 [295  44]
 [288  43]
 [313  44]
 [254  37]
 [295  42]
 [295  42]
 [257  39]
 [234  35]] [[299.    38.46]
 [232.    31.72]
 [293.    42.47]
 [296.    49.41]
 [232.    37.16]
 [219.    33.13]
 [254.    43.1 ]
 [259.    38.33]
 [390.    51.48]
 [295.    40.96]
 [268.    39.81]
 [320.    41.81]
 [304.    46.37]
 [247.    34.9 ]
 [203.    30.98]
 [239.    37.68]
 [351.    47.62]
 [295.    44.5 ]
 [230.    43.09]
 [241.    43.18]
 [264.    35.67]
 [272.    44.97]
 [251.    36.72]
 [216.    33.17]
 [289.    40.48]
 [320.    48.15]
 [295.    48.45]
 [335.    42.55]
 [274.    36.46]
 [308.    41.44]
 [301.    45.83]
 [232.    34.84]
 [224.    30.36]]